### ISSUE TITLE
map values are overwritten

### ISSUE THREAD

**Issue by lukeed** [fisherman/index#9]
In the case of:
```js
parse(['_', 'tasks'])
```
and
```a
./bin first second
```

The `tasks` object will only retain the `second` value. However, parsec's `map` itself is/was populated correctly.

If you add `console.log(map[key])` [here](https://github.com/bucaran/parsec/blob/master/src/index.js#L17), you will see that the value is actually correct:
 `['first', 'second']`.

Beyond that, I'm not sure what's happening as I'm about to step out for the day.

(As you could guess, this affects Fly :wink:)

**Comment by bucaran** [comment]
Will have a look at this. Thanks @lukeed.

BTW I saw the PR, we'll post there later :wink:

**Comment by lukeed** [comment]
No problemo, sounds good.

**Comment by bucaran** [comment]
@lukeed I am testing this at the moment. I'll probably end up rewriting this whole thing. Just installing Parsec and running npm i took like 4 minutes.
